name: Run CodeGuru on OWASP Benchmark

on: [push, pull_request]
permissions:
    id-token: write
    contents: read
    security-events: write 

jobs:

  subprojects:
    name: Analyze Subprojects
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - project: smithy-aws-apigateway-openapi
          - project: smithy-aws-apigateway-traits
          - project: smithy-aws-cloudformation
          - project: smithy-aws-cloudformation-traits
          - project: smithy-aws-iam-traits
          - project: smithy-aws-protocol-tests
          - project: smithy-aws-traits
          - project: smithy-build
          - project: smithy-cli
          - project: smithy-codegen-core
          - project: smithy-diff
          - project: smithy-jmespath
          - project: smithy-jsonschema
          - project: smithy-linters
          - project: smithy-model
          - project: smithy-mqtt-traits
          - project: smithy-openapi
          - project: smithy-protocol-test-traits
          - project: smithy-utils
          - project: smithy-validation-model
          - project: smithy-waiters
    steps:
    - name: Checkout the code and submodules
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: 'true'

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Compile
      run: ./gradlew compileJava -x test

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::048169001733:role/GuruGitHubCICDRole
        aws-region: us-west-2

    - name: CodeGuru Reviewer
      uses: aws-actions/codeguru-reviewer@v1.1
      continue-on-error: false
      with:          
        s3_bucket: codeguru-reviewer-github-profiler-demo-048169001733-uw2
        build_path: ./${{ matrix.project }}/build/classes/java
        
    - run: |
        mkdir ./${{ matrix.project }}_findings
        cp ./*.json ./${{ matrix.project }}_findings || true
    - name: Store Findings
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.project }}_findings
        path: ./${{ matrix.project }}_findings

  upload_sarif:
    name: Merge findings for all subprojects
    runs-on: ubuntu-latest
    needs: 
      - subprojects
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: 'true'
    # Download the artifacts AFTER the checkout, otherwise the git checkout will override the
    # content of this folder.
    - name: Download all aritfacts
      uses: actions/download-artifact@v2
      id: download_findings
      with:
        path: ./     

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: "Create Scorecard"
      run: > 
        jq -rs '{runs: [ {tool: { driver: { rules : (([.[].runs[0].tool.driver.rules]) | flatten) } } , results: (([.[].runs[0].results]) | flatten) } ]  }' $(find . -type f -name "codeguru-results.sarif.json" )  > combined.json

    - name: Upload review result
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: combined.json
